[features]
seeds = false
skip-lint = false
[programs.devnet]
mint_nft = "FqzHmkbeXAHZ2zQzJ6GiQsrYKECbmmpPoHaXYCCB1RmT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/raja/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
